services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    shm_size: 1gb
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, video, compute ]
